find . -maxdepth 5 \( -type d -o -type f \) \
  -not -path "*/node_modules/*" \
  -not -path "*/public/*" \
  -not -path "*/.git/*" \
  -not -path "*/New folder/*"


./.gitattributes
./.gitignore
./client
./client/.env
./client/eslint.config.js
./client/index.html
./client/node_modules
./client/package-lock.json
./client/package.json
./client/postcss.config.js
./client/public
./client/README.md
./client/src
./client/src/App.css
./client/src/App.jsx
./client/src/App_v0_preRefact.jsx
./client/src/assets
./client/src/assets/beat_s
./client/src/assets/beat_s/beat_num_1.mp3
./client/src/assets/beat_s/beat_num_10.mp3
./client/src/assets/beat_s/beat_num_11.mp3
./client/src/assets/beat_s/beat_num_12.mp3
./client/src/assets/beat_s/beat_num_13.mp3
./client/src/assets/beat_s/beat_num_2.mp3
./client/src/assets/beat_s/beat_num_3.mp3
./client/src/assets/beat_s/beat_num_4.mp3
./client/src/assets/beat_s/beat_num_5.mp3
./client/src/assets/beat_s/beat_num_6.mp3
./client/src/assets/beat_s/beat_num_7.mp3
./client/src/assets/beat_s/beat_num_8.mp3
./client/src/assets/beat_s/beat_num_9.mp3
./client/src/components
./client/src/components/AccomodationCard.jsx
./client/src/components/Analytics.jsx
./client/src/components/ApplyModal.jsx
./client/src/components/CameraAnimator.js
./client/src/components/cards
./client/src/components/cards/PriceCard.jsx
./client/src/components/cards/PropertyCard.jsx
./client/src/components/cards/PropertyDetails.jsx
./client/src/components/cards/TourDatePicker.jsx
./client/src/components/entities
./client/src/components/entities/explosion_.js
./client/src/components/entities/fromThreejs_spotlight_extension_1.js
./client/src/components/entities/Text_ENplusFA.js
./client/src/components/entities/WordGen.js
./client/src/components/FavoriteAccommodations.jsx
./client/src/components/Features.jsx
./client/src/components/Footer.jsx
./client/src/components/FreestyleNavbar.jsx
./client/src/components/gallery
./client/src/components/gallery/AccommodationGallery.jsx
./client/src/components/Hero.jsx
./client/src/components/HeroSection.jsx
./client/src/components/Layout.jsx
./client/src/components/managers
./client/src/components/managers/AudioManager.js
./client/src/components/managers/AudioManager_v0_preRefact.js
./client/src/components/managers/BPMManager.js
./client/src/components/managers/BPMManager_v0_preRefact.js
./client/src/components/maps
./client/src/components/maps/Map.jsx
./client/src/components/maps/MapInput.jsx
./client/src/components/maps/PopupContent.jsx
./client/src/components/Navbar.jsx
./client/src/components/OAuth.jsx
./client/src/components/ParticlesBackground.jsx
./client/src/components/PrivateRoute.jsx
./client/src/components/ProfileCard.jsx
./client/src/components/ProfileDropdown.jsx
./client/src/components/PropertyListing.jsx
./client/src/components/Renderer.jsx
./client/src/components/RentalProcess.jsx
./client/src/components/RequireAuth.jsx
./client/src/components/scrolltop.jsx
./client/src/components/SearchBar.jsx
./client/src/components/TourModal.jsx
./client/src/components/UnisGrid.jsx
./client/src/components/VirtualTour.jsx
./client/src/config
./client/src/config/firebase.js
./client/src/contexts
./client/src/contexts/AuthContext.jsx
./client/src/data.json
./client/src/hooks
./client/src/hooks/useSongs.js
./client/src/index.css
./client/src/main.jsx
./client/src/New folder
./client/src/pages
./client/src/pages/About.jsx
./client/src/pages/Accommodation.jsx
./client/src/pages/AccommodationEdit.jsx
./client/src/pages/AccommodationListing.jsx
./client/src/pages/ApplyOnline.jsx
./client/src/pages/ArtistProfile.jsx
./client/src/pages/FAQ.jsx
./client/src/pages/ForgotPasswordOTP.jsx
./client/src/pages/Freestyle.jsx
./client/src/pages/HelpCenter.jsx
./client/src/pages/Home.jsx
./client/src/pages/Leaderboard.jsx
./client/src/pages/NegotiateRent.jsx
./client/src/pages/newChat.jsx
./client/src/pages/NotFound.jsx
./client/src/pages/PayRent.jsx
./client/src/pages/Profile.jsx
./client/src/pages/ResetPasswordOTP.jsx
./client/src/pages/ScheduleTour.jsx
./client/src/pages/SearchResult.jsx
./client/src/pages/SignIn.jsx
./client/src/pages/SignUp.jsx
./client/src/pages/template.jsx
./client/src/pages/template2.jsx
./client/src/pages/UserProfile.jsx
./client/src/pages/VerifyOTP.jsx
./client/src/pytho
./client/src/pytho/audio_process.py
./client/src/pytho/better_output.mid
./client/src/pytho/big.txt
./client/src/pytho/fresnel.py
./client/src/pytho/output.mid
./client/src/pytho/rhyme_words_en.py
./client/src/pytho/similar_words_en.py
./client/src/pytho/wordgen.py
./client/src/pytho/__pycache__
./client/src/pytho/__pycache__/wordgen.cpython-312.pyc
./client/src/redux
./client/src/redux/store.js
./client/src/redux/user
./client/src/redux/user/userSlice.js
./client/src/scss
./client/src/scss/includes
./client/src/scss/includes/base.scss
./client/src/scss/includes/reset.scss
./client/src/scss/style.scss
./client/src/utils
./client/src/utils/audioUtils.js
./client/src/utils/classNames.js
./client/src/utils/EasingFunctions.js
./client/src/utils/timeFormatter.js
./client/src/utils/WordGen.js
./client/src/utils/WordGenerator.js
./client/tailwind.config.js
./client/vite.config.js
./directory-structure.txt
./HierarchyComman_Find_exclude_maxDepth.bash
./LICENSE
./node_modules
./package-lock.json
./package.json
./README.md
./screenshots
./screenshots/homepage.jpeg
./screenshots/homepage.png
./screenshots/listing.jpeg
./screenshots/loginpage.jpeg
./screenshots/web-demo-03.png
./server
./server/.env
./server/config
./server/config/cloudinaryConfig.js
./server/config/db.js
./server/config/PostgreSQL_db.js
./server/controllers
./server/controllers/accommodationController.js
./server/controllers/authController.js
./server/controllers/conversationController.js
./server/controllers/listingController.js
./server/controllers/messageController.js
./server/controllers/PostgreSQLControllerS.js
./server/controllers/universityController.js
./server/controllers/userController.js
./server/middleware
./server/middleware/authMiddleware.js
./server/middleware/multer.js
./server/models
./server/models/accommodationModel.js
./server/models/conversationModel.js
./server/models/messageModel.js
./server/models/otpModel.js
./server/models/PostgreSQL_AllModels.js
./server/models/PostgreSQL_userModel.js
./server/models/universityModel.js
./server/models/userModel.js
./server/MongoAtlas_cred.png
./server/Mongo_conString.txt
./server/node_modules
./server/package-lock.json
./server/package.json
./server/routes
./server/routes/accommodationRoutes.js
./server/routes/authRoutes.js
./server/routes/conversationRoutes.js
./server/routes/listingRoutes.js
./server/routes/messageRoutes.js
./server/routes/PostgreSQLRoutes.js
./server/routes/universityRoutes.js
./server/routes/userRoutes.js
./server/server.js
./server/services
./server/services/beatSyncService.js
./server/utils
./server/utils/errorHandler.js
./server/utils/jwtUtils.js
./server/utils/sendEmail.js
./server/utils/sendSMS.js
./server/youtube_video_info.csv